/**
 * generated by Xtext 2.19.0
 */
package navi.navigationRules;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Coordinate Mapping Spec</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link navi.navigationRules.CoordinateMappingSpec#getControllername <em>Controllername</em>}</li>
 *   <li>{@link navi.navigationRules.CoordinateMappingSpec#getBundleid <em>Bundleid</em>}</li>
 * </ul>
 *
 * @see navi.navigationRules.NavigationRulesPackage#getCoordinateMappingSpec()
 * @model
 * @generated
 */
public interface CoordinateMappingSpec extends MappingSpec
{
  /**
   * Returns the value of the '<em><b>Controllername</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Controllername</em>' attribute.
   * @see #setControllername(String)
   * @see navi.navigationRules.NavigationRulesPackage#getCoordinateMappingSpec_Controllername()
   * @model
   * @generated
   */
  String getControllername();

  /**
   * Sets the value of the '{@link navi.navigationRules.CoordinateMappingSpec#getControllername <em>Controllername</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Controllername</em>' attribute.
   * @see #getControllername()
   * @generated
   */
  void setControllername(String value);

  /**
   * Returns the value of the '<em><b>Bundleid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bundleid</em>' attribute.
   * @see #setBundleid(String)
   * @see navi.navigationRules.NavigationRulesPackage#getCoordinateMappingSpec_Bundleid()
   * @model
   * @generated
   */
  String getBundleid();

  /**
   * Sets the value of the '{@link navi.navigationRules.CoordinateMappingSpec#getBundleid <em>Bundleid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bundleid</em>' attribute.
   * @see #getBundleid()
   * @generated
   */
  void setBundleid(String value);

} // CoordinateMappingSpec
