/**
 * generated by Xtext 2.19.0
 */
package navi.navigationRules;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Destination</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link navi.navigationRules.Destination#getTransition <em>Transition</em>}</li>
 *   <li>{@link navi.navigationRules.Destination#getTarget <em>Target</em>}</li>
 *   <li>{@link navi.navigationRules.Destination#getPermissions <em>Permissions</em>}</li>
 * </ul>
 *
 * @see navi.navigationRules.NavigationRulesPackage#getDestination()
 * @model
 * @generated
 */
public interface Destination extends EObject
{
  /**
   * Returns the value of the '<em><b>Transition</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transition</em>' reference.
   * @see #setTransition(TransitionDefinition)
   * @see navi.navigationRules.NavigationRulesPackage#getDestination_Transition()
   * @model
   * @generated
   */
  TransitionDefinition getTransition();

  /**
   * Sets the value of the '{@link navi.navigationRules.Destination#getTransition <em>Transition</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Transition</em>' reference.
   * @see #getTransition()
   * @generated
   */
  void setTransition(TransitionDefinition value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(CoordinateMappingSpec)
   * @see navi.navigationRules.NavigationRulesPackage#getDestination_Target()
   * @model
   * @generated
   */
  CoordinateMappingSpec getTarget();

  /**
   * Sets the value of the '{@link navi.navigationRules.Destination#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(CoordinateMappingSpec value);

  /**
   * Returns the value of the '<em><b>Permissions</b></em>' containment reference list.
   * The list contents are of type {@link navi.navigationRules.PermissionReference}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Permissions</em>' containment reference list.
   * @see navi.navigationRules.NavigationRulesPackage#getDestination_Permissions()
   * @model containment="true"
   * @generated
   */
  EList<PermissionReference> getPermissions();

} // Destination
