/**
 * generated by Xtext 2.19.0
 */
package navi.navigationRules;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mapping</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see navi.navigationRules.NavigationRulesPackage#getMapping()
 * @model
 * @generated
 */
public interface Mapping extends EObject
{
} // Mapping
