/**
 * generated by Xtext 2.19.0
 */
package navi.navigationRules;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mapping Spec</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link navi.navigationRules.MappingSpec#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see navi.navigationRules.NavigationRulesPackage#getMappingSpec()
 * @model
 * @generated
 */
public interface MappingSpec extends Mapping
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see navi.navigationRules.NavigationRulesPackage#getMappingSpec_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link navi.navigationRules.MappingSpec#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // MappingSpec
