/**
 * generated by Xtext 2.19.0
 */
package navi.navigationRules;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Navigation Rules</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link navi.navigationRules.NavigationRules#getRules <em>Rules</em>}</li>
 * </ul>
 *
 * @see navi.navigationRules.NavigationRulesPackage#getNavigationRules()
 * @model
 * @generated
 */
public interface NavigationRules extends EObject
{
  /**
   * Returns the value of the '<em><b>Rules</b></em>' containment reference list.
   * The list contents are of type {@link navi.navigationRules.Rule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rules</em>' containment reference list.
   * @see navi.navigationRules.NavigationRulesPackage#getNavigationRules_Rules()
   * @model containment="true"
   * @generated
   */
  EList<Rule> getRules();

} // NavigationRules
