/**
 * generated by Xtext 2.19.0
 */
package navi.navigationRules;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Permission Mapping Spec</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link navi.navigationRules.PermissionMappingSpec#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see navi.navigationRules.NavigationRulesPackage#getPermissionMappingSpec()
 * @model
 * @generated
 */
public interface PermissionMappingSpec extends MappingSpec
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see navi.navigationRules.NavigationRulesPackage#getPermissionMappingSpec_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link navi.navigationRules.PermissionMappingSpec#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // PermissionMappingSpec
