/**
 * generated by Xtext 2.19.0
 */
package navi.navigationRules;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Root</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link navi.navigationRules.Root#getName <em>Name</em>}</li>
 *   <li>{@link navi.navigationRules.Root#getMappingsdefs <em>Mappingsdefs</em>}</li>
 *   <li>{@link navi.navigationRules.Root#getTransitiondefs <em>Transitiondefs</em>}</li>
 *   <li>{@link navi.navigationRules.Root#getRuledefs <em>Ruledefs</em>}</li>
 * </ul>
 *
 * @see navi.navigationRules.NavigationRulesPackage#getRoot()
 * @model
 * @generated
 */
public interface Root extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see navi.navigationRules.NavigationRulesPackage#getRoot_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link navi.navigationRules.Root#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Mappingsdefs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mappingsdefs</em>' containment reference.
   * @see #setMappingsdefs(Mappings)
   * @see navi.navigationRules.NavigationRulesPackage#getRoot_Mappingsdefs()
   * @model containment="true"
   * @generated
   */
  Mappings getMappingsdefs();

  /**
   * Sets the value of the '{@link navi.navigationRules.Root#getMappingsdefs <em>Mappingsdefs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mappingsdefs</em>' containment reference.
   * @see #getMappingsdefs()
   * @generated
   */
  void setMappingsdefs(Mappings value);

  /**
   * Returns the value of the '<em><b>Transitiondefs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transitiondefs</em>' containment reference.
   * @see #setTransitiondefs(TransitionDefinitions)
   * @see navi.navigationRules.NavigationRulesPackage#getRoot_Transitiondefs()
   * @model containment="true"
   * @generated
   */
  TransitionDefinitions getTransitiondefs();

  /**
   * Sets the value of the '{@link navi.navigationRules.Root#getTransitiondefs <em>Transitiondefs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Transitiondefs</em>' containment reference.
   * @see #getTransitiondefs()
   * @generated
   */
  void setTransitiondefs(TransitionDefinitions value);

  /**
   * Returns the value of the '<em><b>Ruledefs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ruledefs</em>' containment reference.
   * @see #setRuledefs(NavigationRules)
   * @see navi.navigationRules.NavigationRulesPackage#getRoot_Ruledefs()
   * @model containment="true"
   * @generated
   */
  NavigationRules getRuledefs();

  /**
   * Sets the value of the '{@link navi.navigationRules.Root#getRuledefs <em>Ruledefs</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ruledefs</em>' containment reference.
   * @see #getRuledefs()
   * @generated
   */
  void setRuledefs(NavigationRules value);

} // Root
