/**
 * generated by Xtext 2.19.0
 */
package navi.navigationRules;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transition Definitions</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link navi.navigationRules.TransitionDefinitions#getTransitions <em>Transitions</em>}</li>
 * </ul>
 *
 * @see navi.navigationRules.NavigationRulesPackage#getTransitionDefinitions()
 * @model
 * @generated
 */
public interface TransitionDefinitions extends EObject
{
  /**
   * Returns the value of the '<em><b>Transitions</b></em>' containment reference list.
   * The list contents are of type {@link navi.navigationRules.TransitionDefinition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transitions</em>' containment reference list.
   * @see navi.navigationRules.NavigationRulesPackage#getTransitionDefinitions_Transitions()
   * @model containment="true"
   * @generated
   */
  EList<TransitionDefinition> getTransitions();

} // TransitionDefinitions
