/*
 * generated by Xtext 2.19.0
 */
package navi;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class NavigationRulesRuntimeModule extends AbstractNavigationRulesRuntimeModule {
}
