/*
 * generated by Xtext 2.19.0
 */
package navi;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class NavigationRulesStandaloneSetup extends NavigationRulesStandaloneSetupGenerated {

	public static void doSetup() {
		new NavigationRulesStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
