/*
 * generated by Xtext 2.19.0
 */
package navi.validation;

import org.eclipse.xtext.validation.Check;

import navi.navigationRules.Destination;
import navi.navigationRules.NavigationRulesPackage;
import navi.navigationRules.Rule;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class NavigationRulesValidator extends AbstractNavigationRulesValidator {
	
	public static final String SELF_TRANSITION = "selfTransition";

	@Check
	public void checkGreetingStartsWithCapital(Destination destination) {
		Rule rule  = (Rule) destination.eContainer();
		if (destination.getTarget().equals(rule.getSource())) {
			error("Self transitions are not allowed", // this is the error message
					NavigationRulesPackage.Literals.DESTINATION__TARGET, // this is the feature to highlight with a problem
					SELF_TRANSITION); // this is an error code
		}
	}
	
}
