/*
 * generated by Xtext 2.19.0
 */
package navi.validation;


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class NavigationRulesValidator extends AbstractNavigationRulesValidator {
	
//	public static final INVALID_NAME = 'invalidName'
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					NavigationRulesPackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	
}
