/*
 * generated by Xtext 2.19.0
 */
package navi.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import navi.NavigationRulesRuntimeModule;
import navi.NavigationRulesStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class NavigationRulesIdeSetup extends NavigationRulesStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new NavigationRulesRuntimeModule(), new NavigationRulesIdeModule()));
	}
	
}
