/*
 * generated by Xtext 2.19.0
 */
package navi.ui;

import com.google.inject.Injector;
import navi.navigationRules.ui.internal.NavigationRulesActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class NavigationRulesExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(NavigationRulesActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		NavigationRulesActivator activator = NavigationRulesActivator.getInstance();
		return activator != null ? activator.getInjector(NavigationRulesActivator.NAVI_NAVIGATIONRULES) : null;
	}

}
