/*
 * generated by Xtext 2.19.0
 */
package navi.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class NavigationRulesUiModule extends AbstractNavigationRulesUiModule {

	public NavigationRulesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
