/*
 * generated by Xtext 2.19.0
 */
package navi.parser.antlr;

import com.google.inject.Inject;
import navi.parser.antlr.internal.InternalNavigationRulesParser;
import navi.services.NavigationRulesGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class NavigationRulesParser extends AbstractAntlrParser {

	@Inject
	private NavigationRulesGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalNavigationRulesParser createParser(XtextTokenStream stream) {
		return new InternalNavigationRulesParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Root";
	}

	public NavigationRulesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(NavigationRulesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
